version: "3.8"

# Environment to generate project with openapi generator (+40 languages and technologies)

services:
  app:
    image: openapitools/openapi-generator-cli
    command: ./local/generate/go.sh
    volumes:
      - type: bind
        source: .
        target: /local
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    restart: always